/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "plwwvnpttglpcbdrpmak"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsd3d2bnB0dGdscGNiZHJwbWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTQxMDIsImV4cCI6MjA3MjM5MDEwMn0.wArN3-QT8nzvzBBhX-9zf6ymnvVnFxVF7fO0nHm_2QY"